theme="onelight"
[editor]
true-color = true
bufferline="multiple"
auto-save=true

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
[editor.cursor-shape]
insert="bar"



[keys.insert]
j =  {k = "normal_mode"}


[keys.normal]
G="goto_last_line"
H="goto_line_start"
L="goto_line_end"
V=["extend_to_line_bounds","select_mode"]
"C-h"="jump_view_left"
"C-l"="jump_view_right"
"C-j"="jump_view_down"
"C-k"="jump_view_up"
"C-p"="file_picker"
"tab"=":bn"
"S-tab"=":bp"
[keys.select]
G="goto_last_line"
H="goto_line_start"
L="goto_line_end"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
[editor.lsp]
display-inlay-hints=true

