
[general]
import = ["~/.config/alacritty/active.toml"]

[font]
size = 13.0

[font.normal]
family = "VictorMono Nerd Font"
style = "SemiBold"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "FullScreen"
option_as_alt="OnlyLeft"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
[cursor.style]
blinking = "Always"

[env]
ALACRITTY = "true"

