#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    guifont="Fira_Code"
    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filetree_direction="left"
    # my settings
    default_indent=4
    expand_tab=true
    windows_smartclose=''
    windows_leader=';'
    bootstrap_before="myspacevim#before"
    statusline_left_sections=[ 
        'winnr',
        'major mode',
        'filename',
        'fileformat',
    ]
    statusline_right_sections=[ 
        'time'
    ]


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name="leaderf"

[[layers]]
name="ui"

[[layers]]
name="default"

[[layers]]
name="core#statusline"

# language servers
[[layers]]
name="lang#c"

[[layers]]
name="markdown"

