gui:
  # # stuff relating to the UI
  # scrollHeight: 2 # how many lines you scroll by
  # scrollPastBottom: true # enable scrolling past the bottom
  # sidePanelWidth: 0.3333 # number from 0 to 1
  # expandFocusedSidePanel: false
  # mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
  language: 'zh' # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
