lastupdatecheck: 0
recentrepos:
- /home/yonchicy/my-dot-file
- /home/yonchicy/learnTensorFlow
- /home/yonchicy/compiler/easycc
- /home/yonchicy/compiler/hblzbd_compiler
- /home/yonchicy/compiler/chibicc
- /home/yonchicy/compiler/minidecaf
- /home/yonchicy/tools/dwm
- /home/yonchicy/tools/st-0.8.5
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
