vsync=false
title-hidden=true
[font]
size = 13
hinting = "full"
edging = "antialias"
[font.features]
"Maple Mono SC NF" = ["+cv01","+cv02","+cv04","+ss01", "+ss02", "+ss03","+ss04","+ss05","+calt","+zero","+onum"]



[[font.normal]]
family = "Maple Mono SC NF"
style = "W600"



# [[font.bold]]
# family = "JetBrainsMono Nerd Font Propo"
# style = "W600"

# No need to specify fallback in every variant, if omitted or specified here
# but not found, it will fallback to normal font with this weight which is bold
# in this case.
